[package]
name = "text-editor"
version = "0.1.0"
edition = "2024"

[dependencies]
crossterm = "0.29.0" # For terminal input/output and control
tui = "0.19"         # For building terminal user interfaces
